services:
  db:
    container_name: postgres
    image: postgres
    environment:
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - db:/data/postgres
    ports:
      - "9999:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db:
